{% set name = "pegasus-wms.common" %}
{% set version = "5.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9325ac5d6f45bbeee009be85b30b7c149bd2538273e84535ce8b242fc22fbb9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - pyyaml >5.3

test:
  requires:
    - pip
  imports:
    - Pegasus.braindump
    - Pegasus.client
    - Pegasus.json
    - Pegasus.yaml
  commands:
    - python -m pip check

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
