{% set name = "pegasus-wms.common" %}
{% set version = "5.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f729a6095a749ba2afe30d147dd3ca817992f1c6042b80f95ee6ab03e5ee0745

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools <69
    - wheel
  run:
    - python >={{ python_min }}
    - pyyaml >5.3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - Pegasus.braindump
    - Pegasus.client
    - Pegasus.json
    - Pegasus.yaml
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show pegasus.wms-common

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
