{% set name = "pegasus-wms.common" %}
{% set version = "5.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a831570f75ff8fa411c8b652cb16bc75ecfb606f0a346581d2ff5c9e66b5961

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - pyyaml >5.3

test:
  requires:
    - pip
  imports:
    - Pegasus.braindump
    - Pegasus.client
    - Pegasus.json
    - Pegasus.yaml
  commands:
    # check metadata
    - python -m pip check pegasus.wms-common
    - python -m pip show pegasus.wms-common

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
